Attempt to restore the unitest with the new framework.
I should be able to exclude Qt - which I am not - , so we generate the following
stack : To be resolved!
--------------------------------------------------------------------------------
In file included from main/unitTest/VPPTest.cpp:3:
In file included from main/io/VariableFileParser.h:10:
In file included from main/io/FileParserBase.h:10:
In file included from main/io/Variables.h:10:
main/gui/VariableTreeModel.h:4:10: fatal error: 'QAbstractItemModel' file not found
#include <QAbstractItemModel>
--------------------------------------------------------------------------------